//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class form
    {
        public int Id { get; set; }
        public string name { get; set; }
        public int age { get; set; }
        public int color { get; set; }
        public string quility { get; set; }
    
        public virtual Quility Quility1 { get; set; }
    }
}
