//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quility
    {
        public Quility()
        {
            this.forms = new HashSet<form>();
        }
    
        public int Id { get; set; }
        public string quilityname { get; set; }
        public Nullable<int> colorid { get; set; }
    
        public virtual color color { get; set; }
        public virtual ICollection<form> forms { get; set; }
    }
}
